name: build-test

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
      - "release/**"
  workflow_dispatch:


concurrency: 
  # this ensures after each commit the old jobs are cancelled and the new ones
  # run instead.
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  all-deps:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ["3.8", "3.9", "3.10"]
        requirementsPinned: ["false"]
    uses: ./.github/workflows/test-all-deps.yml@main
    with:
      os: ${{ matrix.os }}
      python: ${{ matrix.python }}
      requirementsPinned: ${{ matrix.requirementsPinned }}
  
  minimal-deps:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ["3.8", "3.9", "3.10"]
    uses: ./.github/workflows/test-minimal-deps.yml@main
    with:
      os: ${{ matrix.os }}
      python: ${{ matrix.python }}
      requirementsPinned: ${{ matrix.requirementsPinned }}

  
  other-ml:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.8"]
        mlpackage: [lightgbm, xgboost, tensorflow, pytorch]
    uses: ./.github/workflows/test-other-ml.yml@main
    with:
      os: ${{ matrix.os }}
      python: ${{ matrix.python }}
      mlpackage: ${{ matrix.mlpackage }}


  linting:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.9"]
    uses: ./.github/workflows/linting.yml@main
    with:
      os: ${{ matrix.os }}
      python: ${{ matrix.python }}
      mlpackage: ${{ matrix.mlpackage }}
